export type Locale = "fr" | "en";

export const copy = {
  fr: {
    brandTagline: "Savoir aujourd’hui. Agir demain.", languageLabel: "Langue", navigation: "Navigation principale", openMenu: "Ouvrir le menu", closeMenu: "Fermer le menu",
    home: "Accueil", explorer: "Explorer", search: "Recherche", favorites: "Favoris", about: "À propos",
    heroOverline: "VOTRE CONNAISSANCE, ÉCLAIRÉE", heroTitleA: "Vos ressources deviennent", heroTitleB: "des connaissances utiles.", heroText: "Une base de connaissances privée qui structure vos ressources, retrouve l’information utile et génère des réponses contextualisées sans exposer vos documents sources.",
    valueSearch: "Recherche intelligente", valueContext: "Réponses contextualisées", valuePrivate: "Documents privés protégés",
    searchOverline: "RECHERCHE TRANSVERSALE", searchTitle: "Que souhaitez-vous comprendre ?", searchText: "Interrogez tout le corpus ou choisissez un Pulse pour affiner la recherche.", searchPlaceholder: "Posez une question à Corpus Campus PAÏA…", searchInputLabel: "Votre question", searchButton: "Lancer la recherche", suggestions: "Suggestions", searchingTitle: "Recherche dans votre corpus…", searchingText: "Les extraits pertinents sont rassemblés avant génération de la réponse.", searchUnavailable: "La recherche est momentanément indisponible.",
    pulseTitle: "Explorer par Pulse", pulseText: "Un filtre facultatif pour cibler un domaine sans enfermer la recherche.", choose: "Choisir",
    libraryOverline: "VOTRE BIBLIOTHÈQUE PRIVÉE", explorerTitle: "Explorer les ressources", explorerText: "Parcourez le corpus à partir de ses métadonnées réelles.", progress: "Progression", parcours: "Parcours", block: "Bloc", module: "Module", resource: "Ressource", chooseParcours: "Choisir un parcours", chooseBlock: "Choisir un bloc", chooseModule: "Choisir un module", catalogLoading: "Chargement du catalogue…", catalogDisconnected: "Catalogue non connecté", catalogDisconnectedText: "Le service de lecture du corpus n’est pas disponible pour le moment.", catalogEmpty: "Aucune ressource disponible", viewSheet: "Consulter la fiche", addFavorite: "Ajouter aux favoris",
    knowledgeSheet: "FICHE DE CONNAISSANCE", generatedFromCorpus: "Réponse générée à partir du corpus privé", resourceSelected: "Cette ressource est sélectionnée dans votre bibliothèque privée.", selectedReason: "Ressource sélectionnée directement dans l’Explorer.", print: "Imprimer / PDF", essential: "L’ESSENTIEL", documentsUsed: "DOCUMENTS MOBILISÉS", sourcesTitle: "Ressources utilisées", sourcesText: "Les références ci-dessous identifient les ressources du corpus associées à cette réponse.", watchStatus: "STATUT DE VÉRIFICATION", watchTitle: "Mise à jour & veille", watchText: "Aucune vérification réglementaire externe n’est revendiquée tant qu’un service de veille tracé n’a pas confirmé la règle, la date et la source officielle.",
    favoritesTitle: "Mes favoris", favoritesText: "Retrouvez les ressources et réponses que vous avez choisies.", answer: "Réponse", removeFavorite: "Retirer des favoris", noFavorites: "Aucun favori pour le moment", noFavoritesText: "Ajoutez une ressource ou une réponse : elle apparaîtra ici.",
    aboutOverline: "À PROPOS", aboutTitle: "Corpus Campus PAÏA", aboutText: "Votre cerveau documentaire personnel : recherche, révision, préparation et compréhension à partir de vos propres ressources, avec une séparation stricte entre les documents privés et ce qui est affiché dans l’interface.",
    piaHelp: "Comment puis-je vous aider ?", piaText: "Je peux vous guider vers une ressource ou remettre le curseur dans la recherche.", askQuestion: "Poser une question", exploreResource: "Explorer une ressource", piaRole: "Compagne de recherche", footer: "Apprendre. Comprendre. Progresser.",
  },
  en: {
    brandTagline: "Know today. Act tomorrow.", languageLabel: "Language", navigation: "Main navigation", openMenu: "Open menu", closeMenu: "Close menu",
    home: "Home", explorer: "Explore", search: "Search", favorites: "Favorites", about: "About",
    heroOverline: "YOUR KNOWLEDGE, ILLUMINATED", heroTitleA: "Turn your resources into", heroTitleB: "useful knowledge.", heroText: "A private knowledge base that structures your resources, retrieves what matters and generates contextual answers without exposing source documents.",
    valueSearch: "Smart search", valueContext: "Contextual answers", valuePrivate: "Protected private documents",
    searchOverline: "CROSS-CORPUS SEARCH", searchTitle: "What would you like to understand?", searchText: "Search the entire corpus or choose a Pulse to narrow the scope.", searchPlaceholder: "Ask Corpus Campus PAÏA a question…", searchInputLabel: "Your question", searchButton: "Search", suggestions: "Suggestions", searchingTitle: "Searching your corpus…", searchingText: "Relevant excerpts are gathered before the answer is generated.", searchUnavailable: "Search is temporarily unavailable.",
    pulseTitle: "Explore by Pulse", pulseText: "An optional filter to focus on a domain without restricting the whole search.", choose: "Choose",
    libraryOverline: "YOUR PRIVATE LIBRARY", explorerTitle: "Explore resources", explorerText: "Browse the corpus using its real metadata.", progress: "Progress", parcours: "Path", block: "Block", module: "Module", resource: "Resource", chooseParcours: "Choose a path", chooseBlock: "Choose a block", chooseModule: "Choose a module", catalogLoading: "Loading catalog…", catalogDisconnected: "Catalog unavailable", catalogDisconnectedText: "The corpus catalog service is not available right now.", catalogEmpty: "No resources available", viewSheet: "View sheet", addFavorite: "Add to favorites",
    knowledgeSheet: "KNOWLEDGE SHEET", generatedFromCorpus: "Answer generated from the private corpus", resourceSelected: "This resource is selected from your private library.", selectedReason: "Resource selected directly from Explorer.", print: "Print / PDF", essential: "THE ESSENTIAL", documentsUsed: "DOCUMENTS USED", sourcesTitle: "Resources used", sourcesText: "The references below identify corpus resources associated with this answer.", watchStatus: "VERIFICATION STATUS", watchTitle: "Updates & monitoring", watchText: "No external regulatory verification is claimed until a traceable monitoring service has confirmed the rule, date and official source.",
    favoritesTitle: "My favorites", favoritesText: "Find the resources and answers you chose to keep.", answer: "Answer", removeFavorite: "Remove favorite", noFavorites: "No favorites yet", noFavoritesText: "Add a resource or answer and it will appear here.",
    aboutOverline: "ABOUT", aboutTitle: "Corpus Campus PAÏA", aboutText: "Your personal documentary brain for search, revision, preparation and understanding based on your own resources, with a strict separation between private documents and what is displayed in the interface.",
    piaHelp: "How can I help?", piaText: "I can guide you to a resource or put the cursor back in search.", askQuestion: "Ask a question", exploreResource: "Explore a resource", piaRole: "Research companion", footer: "Learn. Understand. Progress.",
  },
} as const;
